name: places
description: Shvetsov Kirill

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5 # Модуль для работы с svg изображениями
  surf_lint_rules: ^1.3.0 # Правила Lint, используемые "Surf"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.0 # Инструмент статического анализа, который помогает анализировать и улучшать качество кода.

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/fonts/
    - res/fonts/Roboto/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/roboto_black.ttf
          weight: 900
        - asset: res/fonts/Roboto/roboto_blackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/Roboto/roboto_bold.ttf
          weight: 700
        - asset: res/fonts/Roboto/roboto_boldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/Roboto/roboto_italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Roboto/roboto_light.ttf
          weight: 300
        - asset: res/fonts/Roboto/roboto_lightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Roboto/roboto_medium.ttf
          weight: 500
        - asset: res/fonts/Roboto/roboto_mediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Roboto/roboto_regular.ttf
          weight: 400
        - asset: res/fonts/Roboto/roboto_thin.ttf
          weight: 100
        - asset: res/fonts/Roboto/roboto_thinItalic.ttf
          weight: 100
          style: italic
